name: manage-azure-policy-4d3562da
on:
  workflow_dispatch:
    inputs:
      remarks:
        description: 'Reason for triggering the workflow run'
        required: false
        default: 'Updating Azure Policies'


## Uncomment the following if you wish to automatically trigger workflow run with every commit
#
#  push:
#    paths:
#      - 'policies/Correct_Tag_value_b5725656-a824-4e73-9158-33f303003ebd/**'
#      - 'initiatives/Correct_Tags_on_resources_23493be8d58847b590ec9a90/**'
#      - .github/workflows/manage-azure-policy-4d3562da.yml
jobs:
  apply-azure-policy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Login to Azure
      uses: azure/login@v1
      with:
        creds: ${{secrets.AZURE_CREDENTIALS_4d3562da}}
        allow-no-subscriptions: true
    - name: Create or Update Azure Policies
      uses: azure/manage-azure-policy@v0
      with:
        paths: |
          policies/Correct_Tag_value_b5725656-a824-4e73-9158-33f303003ebd/**
          initiatives/Correct_Tags_on_resources_23493be8d58847b590ec9a90/**
