name: manage-azure-policy-8abf86f6
on:
  workflow_dispatch:
    inputs:
      remarks:
        description: 'Reason for triggering the workflow run'
        required: false
        default: 'Updating Azure Policies'


## Uncomment the following if you wish to automatically trigger workflow run with every commit
#
#  push:
#    paths:
#      - 'policies/Correct_Tag_on_Resource_Group_c4da9574-70ed-45e4-81c2-272fc512c9e9/**'
#      - .github/workflows/manage-azure-policy-8abf86f6.yml
jobs:
  apply-azure-policy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Login to Azure
      uses: azure/login@v1
      with:
        creds: ${{secrets.AZURE_CREDENTIALS_8abf86f6}}
        allow-no-subscriptions: true
    - name: Create or Update Azure Policies
      uses: azure/manage-azure-policy@v0
      with:
        paths: |
          policies/Correct_Tag_on_Resource_Group_c4da9574-70ed-45e4-81c2-272fc512c9e9/**
